use_frameworks!
swift_version = '5.0'
platform :ios, '10.0'

target 'DribbbleTextField_Example' do
  pod 'DribbbleTextField', :path => '../'

  target 'DribbbleTextField_Tests' do
    inherit! :search_paths


  end
end
